export const images: { [key: string]: string } = {
  none: '',
  A:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Sign_language_A.svg/256px-Sign_language_A.svg.png',
  B:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Sign_language_B.svg/128px-Sign_language_B.svg.png',

  C:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sign_language_C.svg/256px-Sign_language_C.svg.png',
  D:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Sign_language_D.svg/128px-Sign_language_D.svg.png',
  E:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sign_language_E.svg/256px-Sign_language_E.svg.png',
  F:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Sign_language_F.svg/128px-Sign_language_F.svg.png',
  G:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Sign_language_G.svg/256px-Sign_language_G.svg.png',
  H:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Sign_language_H.svg/256px-Sign_language_H.svg.png',
  I:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sign_language_I.svg/256px-Sign_language_I.svg.png',
  J:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Sign_language_J.svg/256px-Sign_language_J.svg.png',
  K:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Sign_language_K.svg/256px-Sign_language_K.svg.png',
  L:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Sign_language_L.svg/256px-Sign_language_L.svg.png',
  M:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Sign_language_M.svg/256px-Sign_language_M.svg.png',
  N:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sign_language_N.svg/256px-Sign_language_N.svg.png',
  O:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sign_language_O.svg/256px-Sign_language_O.svg.png',
  P:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Sign_language_P.svg/256px-Sign_language_P.svg.png',
  Q:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Sign_language_Q.svg/256px-Sign_language_Q.svg.png',
  R:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Sign_language_R.svg/128px-Sign_language_R.svg.png',
  S:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Sign_language_S.svg/256px-Sign_language_S.svg.png',
  T:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Sign_language_T.svg/256px-Sign_language_T.svg.png',
  U:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Sign_language_U.svg/128px-Sign_language_U.svg.png',
  V:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sign_language_V.svg/128px-Sign_language_V.svg.png',
  W:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Sign_language_W.svg/128px-Sign_language_W.svg.png',
  X:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Sign_language_X.svg/256px-Sign_language_X.svg.png',
  Y:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Sign_language_Y.svg/256px-Sign_language_Y.svg.png',
  Z:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sign_language_Z.svg/256px-Sign_language_Z.svg.png'
};
