name: slt
channels:
  - pytorch
  - chen
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.5
  - autopep8=1.5.5
  - bcrypt=3.2.0
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - click=7.1.2
  - cudatoolkit=11.0.221
  - dataclasses=0.7
  - flake8=3.8.4
  - flask=1.1.2
  - flask-bcrypt=0.7.1
  - flask-cors=3.0.9
  - flask-jwt-extended=4.0.2
  - flask-pymongo=0.5.1
  - freetype=2.10.4
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - isort=5.7.0
  - itsdangerous=1.1.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9b
  - lazy-object-proxy=1.5.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - parso=0.8.1
  - pillow=8.1.0
  - pip=21.0.1
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pyjwt=2.0.1
  - pylint=2.7.0
  - pymongo=3.11.3
  - python=3.6.12
  - python-dotenv=0.15.0
  - python_abi=3.6
  - pytorch=1.7.1
  - readline=8.1
  - rope=0.18.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
