name: slt
channels:
  - chen
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.5
  - autopep8=1.5.5
  - bcrypt=3.2.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - click=7.1.2
  - flake8=3.8.4
  - flask=1.1.2
  - flask-bcrypt=0.7.1
  - flask-cors=3.0.9
  - flask-jwt-extended=4.0.2
  - flask-pymongo=0.5.1
  - importlib-metadata=2.0.0
  - isort=5.7.0
  - itsdangerous=1.1.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - lazy-object-proxy=1.5.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - ncurses=6.2
  - openssl=1.1.1j
  - parso=0.8.1
  - pip=21.0.1
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pyjwt=2.0.1
  - pylint=2.7.0
  - pymongo=3.11.3
  - python=3.6.12
  - python-dotenv=0.15.0
  - python_abi=3.6
  - readline=8.1
  - rope=0.18.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.2
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zipp=3.4.0
  - zlib=1.2.11
